default_min_depth = 9
default_max_depth = 31
default_latitude = 30
default_height = 0

MIN_PROBE_DEPTH_FOR_CALC = 10
MAX_PROBE_DEPTH_FOR_CALC = 35
SM_HOURLY_DIFF_FIRST_DEPTH = 0.5
SM_HOURLY_DIFF_SECOND_DEPTH = 0.25
MIN_IRR_AMOUNT = 1
MIN_IRR_AMOUNT_SPRINKLER = 5
MAX_RESPONDING_EVENTS = 1
LOW_RESPONSE_FACTOR = 0.5
IRR_SPAN_END_AFTER_X_HOURS = 4
MAX_PCT_NOT_RESPONDING = 0.9
EVENT_MAX_DIFF = 0.5
LOW_RESPONSE_MIN_SM_DIFF = 1
MAX_FAIL_TECHNICAL_DAYS = 3
MIN_PCT_OF_SM_HOURLY_VALUES = 0.70

#SCORE
MIN_SM_DIFF = 5
###
debug_ = False
sql_debug = False
