default_min_depth = 9
default_max_depth = 31
default_latitude = 30
default_height = 0

SM_HOURLY_DIFF_FIRST_DEPTH = 0.5
SM_HOURLY_DIFF_SECOND_DEPTH = 0.25
MIN_IRR_AMOUNT = 1
MAX_RESPONDING_EVENTS = 1
LOW_RESPONSE_FACTOR = 0.5
IRR_SPAN_END_AFTER_X_HOURS = 4
LOW_RESPONSE_MIN_SM_DIFF = 1