default_min_depth = 9
default_max_depth = 31
default_latitude = 30
default_height = 0

DAYS_PERIOD_TO_FETCH = 14
MIN_SM_WEEKLY_DIFF = 10
MIN_SM_SATURATION = 25
MIN_PROBE_DEPTH_FOR_CALC = 10
MAX_PROBE_DEPTH_FOR_CALC = 35
SM_HOURLY_DIFF_FIRST_DEPTH = 0.5
SM_HOURLY_DIFF_SECOND_DEPTH = 0.25
MIN_IRR_AMOUNT = 1 # (0.04 inch)
MIN_IRR_AMOUNT_SPRINKLER = 5 # (0.2 inch)
MAX_RESPONDING_EVENTS = 1
LOW_RESPONSE_FACTOR = 0.5
IRR_SPAN_END_AFTER_X_HOURS = 4
MAX_PCT_NOT_RESPONDING = 0.9
EVENT_MAX_DIFF = 0.5
LOW_RESPONSE_MIN_SM_DIFF = 1
MAX_FAIL_TECHNICAL_DAYS = 3
MIN_PCT_OF_SM_HOURLY_VALUES = 0.70
MIN_HR_DIFF_BETWEEN_IRR_EVENTS = 2

#SCORE
MIN_SM_DIFF = 5

# responding w/o irrigation
SM_HOURLY_DIFF_wo_IRR = 1
system_types_to_consider = ['drip', 'sprinkler', 'drip2']

debug_ = False
sql_debug = False

ENV_NAME = 'local_env'